-- Dados iniciais para random_data
-- Campos: type, theme, country (nullable), gender (nullable), value

-- Nomes MEDIEVAL (10 masc, 10 fem)
INSERT INTO random_data (type, theme, country, gender, value) VALUES
('name', 'medieval', NULL, 'male', 'Aelric'),
('name', 'medieval', NULL, 'male', 'Cedric'),
('name', 'medieval', NULL, 'male', 'Gareth'),
('name', 'medieval', NULL, 'male', 'Osric'),
('name', 'medieval', NULL, 'male', 'Roland'),
('name', 'medieval', NULL, 'male', 'Tristan'),
('name', 'medieval', NULL, 'male', 'Baldric'),
('name', 'medieval', NULL, 'male', 'Edwin'),
('name', 'medieval', NULL, 'male', 'Leofric'),
('name', 'medieval', NULL, 'male', 'Ulric'),
('name', 'medieval', NULL, 'female', 'Elowen'),
('name', 'medieval', NULL, 'female', 'Rowena'),
('name', 'medieval', NULL, 'female', 'Ysabel'),
('name', 'medieval', NULL, 'female', 'Adela'),
('name', 'medieval', NULL, 'female', 'Brigid'),
('name', 'medieval', NULL, 'female', 'Catrin'),
('name', 'medieval', NULL, 'female', 'Elspeth'),
('name', 'medieval', NULL, 'female', 'Isolde'),
('name', 'medieval', NULL, 'female', 'Maeve'),
('name', 'medieval', NULL, 'female', 'Rowan');

-- Nomes FANTASIA (10 masc, 10 fem)
INSERT INTO random_data (type, theme, country, gender, value) VALUES
('name', 'fantasia', NULL, 'male', 'Thalion'),
('name', 'fantasia', NULL, 'male', 'Kael'),
('name', 'fantasia', NULL, 'male', 'Eldric'),
('name', 'fantasia', NULL, 'male', 'Vorin'),
('name', 'fantasia', NULL, 'male', 'Aerendyl'),
('name', 'fantasia', NULL, 'male', 'Malach'),
('name', 'fantasia', NULL, 'male', 'Fenris'),
('name', 'fantasia', NULL, 'male', 'Orion'),
('name', 'fantasia', NULL, 'male', 'Zephryn'),
('name', 'fantasia', NULL, 'male', 'Drystan'),
('name', 'fantasia', NULL, 'female', 'Lyra'),
('name', 'fantasia', NULL, 'female', 'Seraphine'),
('name', 'fantasia', NULL, 'female', 'Nymeria'),
('name', 'fantasia', NULL, 'female', 'Aeris'),
('name', 'fantasia', NULL, 'female', 'Elara'),
('name', 'fantasia', NULL, 'female', 'Morrigan'),
('name', 'fantasia', NULL, 'female', 'Thessa'),
('name', 'fantasia', NULL, 'female', 'Vespera'),
('name', 'fantasia', NULL, 'female', 'Calista'),
('name', 'fantasia', NULL, 'female', 'Selene');

-- Nomes ATUAL por país (10 masc e 10 fem para cada país do app)
INSERT INTO random_data (type, theme, country, gender, value) VALUES
-- Brasil masc
('name', 'atual', 'Brasil', 'male', 'Rafael'),
('name', 'atual', 'Brasil', 'male', 'Gabriel'),
('name', 'atual', 'Brasil', 'male', 'Lucas'),
('name', 'atual', 'Brasil', 'male', 'Mateus'),
('name', 'atual', 'Brasil', 'male', 'Pedro'),
('name', 'atual', 'Brasil', 'male', 'João'),
('name', 'atual', 'Brasil', 'male', 'Caio'),
('name', 'atual', 'Brasil', 'male', 'Thiago'),
('name', 'atual', 'Brasil', 'male', 'Henrique'),
('name', 'atual', 'Brasil', 'male', 'Arthur'),
-- Brasil fem
('name', 'atual', 'Brasil', 'female', 'Camila'),
('name', 'atual', 'Brasil', 'female', 'Marina'),
('name', 'atual', 'Brasil', 'female', 'Beatriz'),
('name', 'atual', 'Brasil', 'female', 'Larissa'),
('name', 'atual', 'Brasil', 'female', 'Carolina'),
('name', 'atual', 'Brasil', 'female', 'Isabela'),
('name', 'atual', 'Brasil', 'female', 'Luiza'),
('name', 'atual', 'Brasil', 'female', 'Bianca'),
('name', 'atual', 'Brasil', 'female', 'Fernanda'),
('name', 'atual', 'Brasil', 'female', 'Helena'),
-- EUA masc
('name', 'atual', 'Estados Unidos', 'male', 'Ethan'),
('name', 'atual', 'Estados Unidos', 'male', 'Liam'),
('name', 'atual', 'Estados Unidos', 'male', 'Noah'),
('name', 'atual', 'Estados Unidos', 'male', 'Mason'),
('name', 'atual', 'Estados Unidos', 'male', 'Logan'),
('name', 'atual', 'Estados Unidos', 'male', 'Caleb'),
('name', 'atual', 'Estados Unidos', 'male', 'Owen'),
('name', 'atual', 'Estados Unidos', 'male', 'Wyatt'),
('name', 'atual', 'Estados Unidos', 'male', 'Carter'),
('name', 'atual', 'Estados Unidos', 'male', 'Hunter'),
-- EUA fem
('name', 'atual', 'Estados Unidos', 'female', 'Madison'),
('name', 'atual', 'Estados Unidos', 'female', 'Ava'),
('name', 'atual', 'Estados Unidos', 'female', 'Sophia'),
('name', 'atual', 'Estados Unidos', 'female', 'Harper'),
('name', 'atual', 'Estados Unidos', 'female', 'Scarlett'),
('name', 'atual', 'Estados Unidos', 'female', 'Chloe'),
('name', 'atual', 'Estados Unidos', 'female', 'Lily'),
('name', 'atual', 'Estados Unidos', 'female', 'Natalie'),
('name', 'atual', 'Estados Unidos', 'female', 'Brooklyn'),
('name', 'atual', 'Estados Unidos', 'female', 'Zoe'),
-- Canadá masc
('name', 'atual', 'Canadá', 'male', 'Evan'),
('name', 'atual', 'Canadá', 'male', 'Noel'),
('name', 'atual', 'Canadá', 'male', 'Olivier'),
('name', 'atual', 'Canadá', 'male', 'Dominic'),
('name', 'atual', 'Canadá', 'male', 'Elliot'),
('name', 'atual', 'Canadá', 'male', 'Logan'),
('name', 'atual', 'Canadá', 'male', 'Mathieu'),
('name', 'atual', 'Canadá', 'male', 'Caleb'),
('name', 'atual', 'Canadá', 'male', 'Nathan'),
('name', 'atual', 'Canadá', 'male', 'Gabriel'),
-- Canadá fem
('name', 'atual', 'Canadá', 'female', 'Amelie'),
('name', 'atual', 'Canadá', 'female', 'Chloe'),
('name', 'atual', 'Canadá', 'female', 'Juliette'),
('name', 'atual', 'Canadá', 'female', 'Sophie'),
('name', 'atual', 'Canadá', 'female', 'Amelia'),
('name', 'atual', 'Canadá', 'female', 'Maeve'),
('name', 'atual', 'Canadá', 'female', 'Olivia'),
('name', 'atual', 'Canadá', 'female', 'Mila'),
('name', 'atual', 'Canadá', 'female', 'Elodie'),
('name', 'atual', 'Canadá', 'female', 'Jasmine'),
-- Japão masc
('name', 'atual', 'Japão', 'male', 'Haruto'),
('name', 'atual', 'Japão', 'male', 'Ren'),
('name', 'atual', 'Japão', 'male', 'Daichi'),
('name', 'atual', 'Japão', 'male', 'Kaito'),
('name', 'atual', 'Japão', 'male', 'Sora'),
('name', 'atual', 'Japão', 'male', 'Yuki'),
('name', 'atual', 'Japão', 'male', 'Takumi'),
('name', 'atual', 'Japão', 'male', 'Riku'),
('name', 'atual', 'Japão', 'male', 'Shinji'),
('name', 'atual', 'Japão', 'male', 'Toshi'),
-- Japão fem
('name', 'atual', 'Japão', 'female', 'Yui'),
('name', 'atual', 'Japão', 'female', 'Sakura'),
('name', 'atual', 'Japão', 'female', 'Hana'),
('name', 'atual', 'Japão', 'female', 'Aiko'),
('name', 'atual', 'Japão', 'female', 'Mei'),
('name', 'atual', 'Japão', 'female', 'Ayumi'),
('name', 'atual', 'Japão', 'female', 'Haruka'),
('name', 'atual', 'Japão', 'female', 'Emiko'),
('name', 'atual', 'Japão', 'female', 'Rina'),
('name', 'atual', 'Japão', 'female', 'Naomi'),
-- México masc
('name', 'atual', 'México', 'male', 'Diego'),
('name', 'atual', 'México', 'male', 'Carlos'),
('name', 'atual', 'México', 'male', 'Javier'),
('name', 'atual', 'México', 'male', 'Emilio'),
('name', 'atual', 'México', 'male', 'Ricardo'),
('name', 'atual', 'México', 'male', 'Fernando'),
('name', 'atual', 'México', 'male', 'Andrés'),
('name', 'atual', 'México', 'male', 'Luis'),
('name', 'atual', 'México', 'male', 'Santiago'),
('name', 'atual', 'México', 'male', 'Mateo'),
-- México fem
('name', 'atual', 'México', 'female', 'Valeria'),
('name', 'atual', 'México', 'female', 'Sofía'),
('name', 'atual', 'México', 'female', 'Camila'),
('name', 'atual', 'México', 'female', 'Mariana'),
('name', 'atual', 'México', 'female', 'Daniela'),
('name', 'atual', 'México', 'female', 'Ximena'),
('name', 'atual', 'México', 'female', 'Natalia'),
('name', 'atual', 'México', 'female', 'Andrea'),
('name', 'atual', 'México', 'female', 'Regina'),
('name', 'atual', 'México', 'female', 'Lucía'),
-- Reino Unido masc
('name', 'atual', 'Reino Unido', 'male', 'Oliver'),
('name', 'atual', 'Reino Unido', 'male', 'Jack'),
('name', 'atual', 'Reino Unido', 'male', 'Harry'),
('name', 'atual', 'Reino Unido', 'male', 'George'),
('name', 'atual', 'Reino Unido', 'male', 'William'),
('name', 'atual', 'Reino Unido', 'male', 'Arthur'),
('name', 'atual', 'Reino Unido', 'male', 'Theo'),
('name', 'atual', 'Reino Unido', 'male', 'Freddie'),
('name', 'atual', 'Reino Unido', 'male', 'Oscar'),
('name', 'atual', 'Reino Unido', 'male', 'Alfie'),
-- Reino Unido fem
('name', 'atual', 'Reino Unido', 'female', 'Olivia'),
('name', 'atual', 'Reino Unido', 'female', 'Amelia'),
('name', 'atual', 'Reino Unido', 'female', 'Isla'),
('name', 'atual', 'Reino Unido', 'female', 'Ava'),
('name', 'atual', 'Reino Unido', 'female', 'Freya'),
('name', 'atual', 'Reino Unido', 'female', 'Daisy'),
('name', 'atual', 'Reino Unido', 'female', 'Poppy'),
('name', 'atual', 'Reino Unido', 'female', 'Sophie'),
('name', 'atual', 'Reino Unido', 'female', 'Chloe'),
('name', 'atual', 'Reino Unido', 'female', 'Mia'),
-- França masc
('name', 'atual', 'França', 'male', 'Louis'),
('name', 'atual', 'França', 'male', 'Pierre'),
('name', 'atual', 'França', 'male', 'Hugo'),
('name', 'atual', 'França', 'male', 'Antoine'),
('name', 'atual', 'França', 'male', 'Gabriel'),
('name', 'atual', 'França', 'male', 'Julien'),
('name', 'atual', 'França', 'male', 'Mathis'),
('name', 'atual', 'França', 'male', 'Luc'),
('name', 'atual', 'França', 'male', 'Etienne'),
('name', 'atual', 'França', 'male', 'Benoit'),
-- França fem
('name', 'atual', 'França', 'female', 'Camille'),
('name', 'atual', 'França', 'female', 'Léa'),
('name', 'atual', 'França', 'female', 'Manon'),
('name', 'atual', 'França', 'female', 'Chloé'),
('name', 'atual', 'França', 'female', 'Juliette'),
('name', 'atual', 'França', 'female', 'Amélie'),
('name', 'atual', 'França', 'female', 'Claire'),
('name', 'atual', 'França', 'female', 'Élise'),
('name', 'atual', 'França', 'female', 'Marion'),
('name', 'atual', 'França', 'female', 'Sophie'),
-- Alemanha masc
('name', 'atual', 'Alemanha', 'male', 'Lukas'),
('name', 'atual', 'Alemanha', 'male', 'Jonas'),
('name', 'atual', 'Alemanha', 'male', 'Felix'),
('name', 'atual', 'Alemanha', 'male', 'Leon'),
('name', 'atual', 'Alemanha', 'male', 'Henrik'),
('name', 'atual', 'Alemanha', 'male', 'Tobias'),
('name', 'atual', 'Alemanha', 'male', 'Marcel'),
('name', 'atual', 'Alemanha', 'male', 'Karl'),
('name', 'atual', 'Alemanha', 'male', 'Dieter'),
('name', 'atual', 'Alemanha', 'male', 'Sebastian'),
-- Alemanha fem
('name', 'atual', 'Alemanha', 'female', 'Lena'),
('name', 'atual', 'Alemanha', 'female', 'Anna'),
('name', 'atual', 'Alemanha', 'female', 'Sophie'),
('name', 'atual', 'Alemanha', 'female', 'Emilia'),
('name', 'atual', 'Alemanha', 'female', 'Mia'),
('name', 'atual', 'Alemanha', 'female', 'Hanna'),
('name', 'atual', 'Alemanha', 'female', 'Greta'),
('name', 'atual', 'Alemanha', 'female', 'Clara'),
('name', 'atual', 'Alemanha', 'female', 'Katrin'),
('name', 'atual', 'Alemanha', 'female', 'Amelie'),
-- Austrália masc
('name', 'atual', 'Austrália', 'male', 'Lachlan'),
('name', 'atual', 'Austrália', 'male', 'Noah'),
('name', 'atual', 'Austrália', 'male', 'Cooper'),
('name', 'atual', 'Austrália', 'male', 'Ethan'),
('name', 'atual', 'Austrália', 'male', 'Riley'),
('name', 'atual', 'Austrália', 'male', 'Harrison'),
('name', 'atual', 'Austrália', 'male', 'Mason'),
('name', 'atual', 'Austrália', 'male', 'Finn'),
('name', 'atual', 'Austrália', 'male', 'Oliver'),
('name', 'atual', 'Austrália', 'male', 'Hudson'),
-- Austrália fem
('name', 'atual', 'Austrália', 'female', 'Isla'),
('name', 'atual', 'Austrália', 'female', 'Charlotte'),
('name', 'atual', 'Austrália', 'female', 'Grace'),
('name', 'atual', 'Austrália', 'female', 'Matilda'),
('name', 'atual', 'Austrália', 'female', 'Zoe'),
('name', 'atual', 'Austrália', 'female', 'Ruby'),
('name', 'atual', 'Austrália', 'female', 'Evie'),
('name', 'atual', 'Austrália', 'female', 'Olivia'),
('name', 'atual', 'Austrália', 'female', 'Sienna'),
('name', 'atual', 'Austrália', 'female', 'Harper');

-- Raças básicas
INSERT INTO random_data (type, theme, country, gender, value) VALUES
('race', 'medieval', NULL, NULL, 'Humano'),
('race', 'fantasia', NULL, NULL, 'Elfo da mata'),
('race', 'fantasia', NULL, NULL, 'Tiefling'),
('race', 'fantasia', NULL, NULL, 'Draconato'),
('race', 'fantasia', NULL, NULL, 'Meio-gigante'),
('race', 'fantasia', NULL, NULL, 'Gnomo das nuvens'),
('race', 'atual', NULL, NULL, 'Humano');

-- Aparências (15 por theme + 10 por país atual)
INSERT INTO random_data (type, theme, country, gender, value) VALUES
-- Medieval
('appearance', 'medieval', NULL, NULL, 'Cicatriz na sobrancelha, cota de malha gasta'),
('appearance', 'medieval', NULL, NULL, 'Barba trançada e manto de lã escura'),
('appearance', 'medieval', NULL, NULL, 'Olhos castanhos firmes, usa um elmo amassado'),
('appearance', 'medieval', NULL, NULL, 'Cabelos compridos presos em couro, veste brigandina'),
('appearance', 'medieval', NULL, NULL, 'Manto de peregrino com símbolos bordados, botas enlameadas'),
('appearance', 'medieval', NULL, NULL, 'Cicatriz de queimadura no antebraço, capa curta de pele'),
('appearance', 'medieval', NULL, NULL, 'Olhos claros e olhar desconfiado, punhos enfaixados'),
('appearance', 'medieval', NULL, NULL, 'Coroa de tranças finas, veste túnica de linho verde-escuro'),
('appearance', 'medieval', NULL, NULL, 'Mãos calejadas, armadura de couro batido, adaga na bota'),
('appearance', 'medieval', NULL, NULL, 'Cabelo raspado dos lados, elmo nasal pendurado no cinto'),
('appearance', 'medieval', NULL, NULL, 'Chapéu de feltro e grimório preso ao cinto'),
('appearance', 'medieval', NULL, NULL, 'Capa azul desbotada, broche de madeira talhada'),
('appearance', 'medieval', NULL, NULL, 'Rosto sardento, elmo aberto e escudo com brasão gasto'),
('appearance', 'medieval', NULL, NULL, 'Vestido simples com avental de couro, pulseiras de metal'),
('appearance', 'medieval', NULL, NULL, 'Espada curta de treino, luvas sem dedos, olhar resoluto'),
-- Fantasia
('appearance', 'fantasia', NULL, NULL, 'Olhos âmbar, tatuagens rúnicas no pescoço'),
('appearance', 'fantasia', NULL, NULL, 'Cabelos prateados, manto esmeralda com bordados dourados'),
('appearance', 'fantasia', NULL, NULL, 'Chifres pequenos, pele acinzentada, veste túnica púrpura'),
('appearance', 'fantasia', NULL, NULL, 'Orelhas longas, armadura leve com folhas encantadas'),
('appearance', 'fantasia', NULL, NULL, 'Escamas discretas no pescoço, olhos felinos'),
('appearance', 'fantasia', NULL, NULL, 'Cajado de cristal, lenço que flutua sozinho'),
('appearance', 'fantasia', NULL, NULL, 'Cabelos azul-escuro, tatuagens luminescentes nos braços'),
('appearance', 'fantasia', NULL, NULL, 'Asa cicatrizada, veste manto preto estrelado'),
('appearance', 'fantasia', NULL, NULL, 'Cordão com dente de dragão, armadura de placas leves'),
('appearance', 'fantasia', NULL, NULL, 'Manto de plumas, olhos dourados, máscara meia-face'),
('appearance', 'fantasia', NULL, NULL, 'Runas flutuam ao redor dos punhos, botas de couro vermelho'),
('appearance', 'fantasia', NULL, NULL, 'Rabo felpudo, capa curta de viagem, sorriso travesso'),
('appearance', 'fantasia', NULL, NULL, 'Vestes de seda azul profundo, tiara com pedra lunar'),
('appearance', 'fantasia', NULL, NULL, 'Cabelos verdes, pele levemente pétrea, veste túnica terrosa'),
('appearance', 'fantasia', NULL, NULL, 'Olhos como brasas, armadura escura com veios carmesim'),
-- Atual (Brasil e EUA juntos)
('appearance', 'atual', 'Brasil', NULL, 'Jaqueta de couro, tênis surrados, headphone no pescoço'),
('appearance', 'atual', 'Brasil', NULL, 'Moletom largo, tatuagem minimalista no antebraço'),
('appearance', 'atual', 'Brasil', NULL, 'Óculos redondos, tote bag com livros, tênis branco'),
('appearance', 'atual', 'Brasil', NULL, 'Colete jeans, pulseiras de couro, mochila de trilha'),
('appearance', 'atual', 'Brasil', NULL, 'Cabelo cacheado preso, camisa de banda, all-stars gastros'),
('appearance', 'atual', 'Brasil', NULL, 'Macacão de oficina manchado de graxa, chave inglesa no bolso'),
('appearance', 'atual', 'Brasil', NULL, 'Camisa estampada, chinelos, tereré na mão'),
('appearance', 'atual', 'Brasil', NULL, 'Blazer leve, relógio digital, tablet sempre à mão'),
('appearance', 'atual', 'Brasil', NULL, 'Camisa de time, boné, tornozeleira esportiva'),
('appearance', 'atual', 'Brasil', NULL, 'Tranças coloridas, jaqueta corta-vento, pochete transversal'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Moletom cinza, boné virado, cicatriz discreta no antebraço'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Jaqueta varsity, tênis de corrida, smartwatch'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Blusa xadrez, botas de caminhada, barba por fazer'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Casaco militar vintage, óculos escuros, luvas sem dedos'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Vestido floral, jaqueta de couro, anel de prata'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Calça cargo, coturno, colar de plaqueta'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Jaqueta de couro vermelha, bandana, tatuagem no pescoço'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Camisa social dobrada, suspensórios, óculos retangulares'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Mochila tática, fone over-ear, pulseira de couro'),
('appearance', 'atual', 'Estados Unidos', NULL, 'Suéter oversized, saia jeans, botas ankle'),
-- Canadá
('appearance', 'atual', 'Canadá', NULL, 'Jaqueta acolchoada, gorro de lã, botas para neve'),
('appearance', 'atual', 'Canadá', NULL, 'Camisa xadrez, barba aparada, mochila de trilha'),
('appearance', 'atual', 'Canadá', NULL, 'Parka azul marinho, luvas de couro, cachecol listrado'),
('appearance', 'atual', 'Canadá', NULL, 'Cabelo preso em coque, jaqueta jeans forrada, botas hiking'),
('appearance', 'atual', 'Canadá', NULL, 'Touca de tricô, casaco de lã, copo térmico na mão'),
('appearance', 'atual', 'Canadá', NULL, 'Moletom de universidade, tênis de corrida, fone intra-auricular'),
('appearance', 'atual', 'Canadá', NULL, 'Blusa térmica, colete puffer, mochila com patches'),
('appearance', 'atual', 'Canadá', NULL, 'Cachecol vermelho, casaco impermeável, luvas de esqui'),
('appearance', 'atual', 'Canadá', NULL, 'Cabelo curto desgrenhado, jaqueta de flanela, botas de couro'),
('appearance', 'atual', 'Canadá', NULL, 'Casaco parka verde, óculos de armação preta, tênis de trilha'),
-- Japão
('appearance', 'atual', 'Japão', NULL, 'Uniforme escolar estilizado, tênis branco, mochila minimalista'),
('appearance', 'atual', 'Japão', NULL, 'Kimono casual leve, sandálias zori, cabelo preso com kanzashi'),
('appearance', 'atual', 'Japão', NULL, 'Corte undercut discreto, jaqueta bomber, máscara cirúrgica sob o queixo'),
('appearance', 'atual', 'Japão', NULL, 'Casaco trench bege, bolsa tote de tecido, óculos redondos'),
('appearance', 'atual', 'Japão', NULL, 'Sobretudo preto minimalista, cachecol fino, botas Chelsea'),
('appearance', 'atual', 'Japão', NULL, 'Suéter oversized pastel, saia plissada, tênis plataforma'),
('appearance', 'atual', 'Japão', NULL, 'Blazer escolar, crachá pendurado, tablet na mão'),
('appearance', 'atual', 'Japão', NULL, 'Jaqueta techwear, pochete transversal, fones Bluetooth'),
('appearance', 'atual', 'Japão', NULL, 'Cabelo azul-marinho curto, camisa branca, mochila de couro'),
('appearance', 'atual', 'Japão', NULL, 'Casaco de lã cinza, luvas pretas, guarda-chuva dobrável'),
-- México
('appearance', 'atual', 'México', NULL, 'Camisa bordada, chapéu de aba curta, pulseira de contas'),
('appearance', 'atual', 'México', NULL, 'Jaqueta leve, tênis colorido, mochila com estampas de alebrije'),
('appearance', 'atual', 'México', NULL, 'Vestido fresco com flores, sandálias de couro, lenço colorido'),
('appearance', 'atual', 'México', NULL, 'Cabelo preso com lenço, jaqueta jeans, brincos de prata'),
('appearance', 'atual', 'México', NULL, 'Camisa guayabera clara, calça chino, mocassins'),
('appearance', 'atual', 'México', NULL, 'Poncho moderno, botas de cano curto, cinto trabalhado'),
('appearance', 'atual', 'México', NULL, 'Moletom com arte de mural, boné aba reta, tênis esportivo'),
('appearance', 'atual', 'México', NULL, 'Blusa off-shoulder com bordado, saia midi, sandálias de tiras'),
('appearance', 'atual', 'México', NULL, 'Jaqueta de couro marrom, camisa de linho, colar de contas'),
('appearance', 'atual', 'México', NULL, 'Cabelo cacheado volumoso, camiseta de time local, pulseiras coloridas'),
-- Reino Unido
('appearance', 'atual', 'Reino Unido', NULL, 'Trench coat bege, cachecol xadrez, guarda-chuva fechado'),
('appearance', 'atual', 'Reino Unido', NULL, 'Sobretudo de lã, boina, luvas de couro, sapatos Oxford'),
('appearance', 'atual', 'Reino Unido', NULL, 'Jaqueta de couro preta, calça skinny, botas Chelsea'),
('appearance', 'atual', 'Reino Unido', NULL, 'Blazer de tweed, suéter de gola V, mochila de couro'),
('appearance', 'atual', 'Reino Unido', NULL, 'Cabelo ruivo ondulado, capa de chuva, botas de borracha'),
('appearance', 'atual', 'Reino Unido', NULL, 'Casaco xadrez, cachecol grosso, óculos arredondados'),
('appearance', 'atual', 'Reino Unido', NULL, 'Moletom de banda indie, jaqueta jeans, tênis gasto'),
('appearance', 'atual', 'Reino Unido', NULL, 'Vestido floral escuro, meia-calça preta, coturnos'),
('appearance', 'atual', 'Reino Unido', NULL, 'Corte social curto, casaco marinho, pasta de couro'),
('appearance', 'atual', 'Reino Unido', NULL, 'Suéter de tricô verde-musgo, calça de alfaiataria, botas brogue'),
-- França
('appearance', 'atual', 'França', NULL, 'Boina preta, camisa listrada, lenço no pescoço'),
('appearance', 'atual', 'França', NULL, 'Trench coat bege, bolsa de couro, sapatilhas'),
('appearance', 'atual', 'França', NULL, 'Blazer leve, camiseta branca, calça cigarette'),
('appearance', 'atual', 'França', NULL, 'Cabelo preso em coque baixo, vestido midi, óculos redondos'),
('appearance', 'atual', 'França', NULL, 'Jaqueta de couro marrom, cachecol de lã, botas cano médio'),
('appearance', 'atual', 'França', NULL, 'Camisa de linho, suspensórios, sapatos derby'),
('appearance', 'atual', 'França', NULL, 'Cardigã azul-marinho, tote bag de mercado, tênis branco'),
('appearance', 'atual', 'França', NULL, 'Blusa de gola alta, saia plissada, meia-calça'),
('appearance', 'atual', 'França', NULL, 'Chapéu cloche, casaco longo, luvas finas'),
('appearance', 'atual', 'França', NULL, 'Cabelo cacheado curto, blazer xadrez, sapatos Oxford claros'),
-- Alemanha
('appearance', 'atual', 'Alemanha', NULL, 'Jaqueta de couro marrom, cachecol de lã grossa, botas robustas'),
('appearance', 'atual', 'Alemanha', NULL, 'Casaco parka, mochila funcional, tênis de caminhada'),
('appearance', 'atual', 'Alemanha', NULL, 'Cardigã cinza, camisa branca, calça reta escura'),
('appearance', 'atual', 'Alemanha', NULL, 'Corte lateral curto, jaqueta impermeável, botas pretas'),
('appearance', 'atual', 'Alemanha', NULL, 'Suéter de gola alta, casaco de lã verde-escuro, sapatos derby'),
('appearance', 'atual', 'Alemanha', NULL, 'Camisa xadrez, colete acolchoado, tênis trail'),
('appearance', 'atual', 'Alemanha', NULL, 'Macacão de trabalho cinza com cinto de ferramentas e luvas de couro'),
('appearance', 'atual', 'Alemanha', NULL, 'Blazer escuro, mochila slim, óculos retangulares'),
('appearance', 'atual', 'Alemanha', NULL, 'Vestido preto simples, jaqueta jeans, botas ankle'),
('appearance', 'atual', 'Alemanha', NULL, 'Casaco de lã longo, cachecol listrado, gorro de tricô'),
-- Austrália
('appearance', 'atual', 'Austrália', NULL, 'Camiseta leve, shorts de surf, chinelos de dedo'),
('appearance', 'atual', 'Austrália', NULL, 'Chapéu bucket, regata, bermuda cargo, chinelos'),
('appearance', 'atual', 'Austrália', NULL, 'Rash guard, óculos de sol, sandálias de praia'),
('appearance', 'atual', 'Austrália', NULL, 'Camiseta de time de rúgbi, boné, tênis esportivo'),
('appearance', 'atual', 'Austrália', NULL, 'Vestido leve de linho, chapéu de palha, sandálias'),
('appearance', 'atual', 'Austrália', NULL, 'Camisa floral, bermuda, colar de conchas'),
('appearance', 'atual', 'Austrália', NULL, 'Jaqueta corta-vento, mochila de trilha, botas leves'),
('appearance', 'atual', 'Austrália', NULL, 'Cabelo preso, regata esportiva, garrafa térmica pendurada'),
('appearance', 'atual', 'Austrália', NULL, 'Camiseta branca, calça chino clara, tênis slip-on'),
('appearance', 'atual', 'Austrália', NULL, 'Cardigã leve, shorts jeans, sandálias rasteiras');

-- Histórias (15 por theme)
INSERT INTO random_data (type, theme, country, gender, value) VALUES
-- Medieval
('story', 'medieval', NULL, NULL, 'Cresceu como aprendiz de armas e jurou proteger o senhorio após uma emboscada'),
('story', 'medieval', NULL, NULL, 'Vive no exílio por desafiar o conselho e busca recuperar a própria honra'),
('story', 'medieval', NULL, NULL, 'Fugiu de um cerco levando um mapa para um tesouro perdido'),
('story', 'medieval', NULL, NULL, 'Copista de mosteiro que testemunhou um milagre proibido'),
('story', 'medieval', NULL, NULL, 'Artífice do aço que aprendeu a temperar lâminas com fogo de dragão'),
('story', 'medieval', NULL, NULL, 'Vigia com arco na fronteira desde a infância'),
('story', 'medieval', NULL, NULL, 'Combatente contratado que jurou não empunhar lâminas contra inocentes'),
('story', 'medieval', NULL, NULL, 'Praticante de cura que coleta ervas em ruínas assombradas'),
('story', 'medieval', NULL, NULL, 'Portador de mensagens que conhece passagens secretas entre reinos'),
('story', 'medieval', NULL, NULL, 'Artista itinerante que carrega uma balada capaz de invocar tempestades'),
('story', 'medieval', NULL, NULL, 'Pessoa nobre em fuga após recusar um casamento arranjado'),
('story', 'medieval', NULL, NULL, 'Guarda-florestal que perdeu a família para lobos gigantes'),
('story', 'medieval', NULL, NULL, 'Criado em um convento e procura um irmão desaparecido'),
('story', 'medieval', NULL, NULL, 'Portador do estandarte real que salvou a bandeira durante a retirada'),
('story', 'medieval', NULL, NULL, 'Testemunhou um cometa cair e acredita ter uma missão divina'),
-- Fantasia
('story', 'fantasia', NULL, NULL, 'Místico errante que coleciona fragmentos de artefatos antigos'),
('story', 'fantasia', NULL, NULL, 'Artista viajante que canta sobre dragões para esconder um passado nobre'),
('story', 'fantasia', NULL, NULL, 'Guardião de portal selado que se enfraquece a cada eclipse'),
('story', 'fantasia', NULL, NULL, 'Caçador de recompensas que rastreia necromantes'),
('story', 'fantasia', NULL, NULL, 'Estudioso de magia que faz pactos com espíritos da floresta por conhecimento'),
('story', 'fantasia', NULL, NULL, 'Alquimista que perdeu o olfato ao inalar vapores proibidos'),
('story', 'fantasia', NULL, NULL, 'Combatente que sonha com um dragão acorrentado sob a cidade'),
('story', 'fantasia', NULL, NULL, 'Vivente das sombras exilado, sobrevive trocando favores e segredos'),
('story', 'fantasia', NULL, NULL, 'Nômade celeste que navega em uma arca voadora'),
('story', 'fantasia', NULL, NULL, 'Druida que conversa com pedras antigas em troca de memórias'),
('story', 'fantasia', NULL, NULL, 'Oficiante que recebeu um sino que toca sozinho ao perigo'),
('story', 'fantasia', NULL, NULL, 'Guia com arco que leva caravanas por passagens ilusórias'),
('story', 'fantasia', NULL, NULL, 'Pirata do céu que enterrou metade do mapa em outro plano'),
('story', 'fantasia', NULL, NULL, 'Guardião de chamas azuis mantidas dentro de frascos'),
('story', 'fantasia', NULL, NULL, 'Bibliotecário de um arquivo infinito que se move à noite'),
-- Atual (Brasil / EUA)
('story', 'atual', 'Brasil', NULL, 'Investigador independente que documenta lendas urbanas em vídeos'),
('story', 'atual', 'Brasil', NULL, 'Jornalista que desvendou fraudes em licitações e ganhou inimigos'),
('story', 'atual', 'Brasil', NULL, 'Motociclista de entregas que testemunhou algo que não deveria'),
('story', 'atual', 'Brasil', NULL, 'Especialista em segurança digital que mantém um fórum secreto'),
('story', 'atual', 'Brasil', NULL, 'Historiador que caça artefatos coloniais desaparecidos'),
('story', 'atual', 'Brasil', NULL, 'Guia urbano que conhece túneis sob a cidade velha'),
('story', 'atual', 'Brasil', NULL, 'Profissional de resgate que investiga um caso de apagões coletivos'),
('story', 'atual', 'Brasil', NULL, 'Fotógrafo que registrou luzes estranhas no litoral'),
('story', 'atual', 'Brasil', NULL, 'Professor que traduz códices indígenas recém-descobertos'),
('story', 'atual', 'Brasil', NULL, 'Veterano que protege testemunhas em rotas clandestinas'),
('story', 'atual', 'Estados Unidos', NULL, 'Analista de TI que descobriu um arquivo misterioso e está sendo perseguido'),
('story', 'atual', 'Estados Unidos', NULL, 'Agente de campo aposentado que virou detetive particular'),
('story', 'atual', 'Estados Unidos', NULL, 'Socorrista que presenciou um acidente impossível de explicar'),
('story', 'atual', 'Estados Unidos', NULL, 'Criador de podcast que investiga casos frios e recebe dicas anônimas'),
('story', 'atual', 'Estados Unidos', NULL, 'Cartógrafo urbano que rastreia túneis esquecidos de metrô'),
('story', 'atual', 'Estados Unidos', NULL, 'Engenheiro elétrico que nota padrões em quedas de energia'),
('story', 'atual', 'Estados Unidos', NULL, 'Bibliotecário que encontra bilhetes cifrados em devoluções'),
('story', 'atual', 'Estados Unidos', NULL, 'Piloto de drone que filmou um ritual em zona industrial'),
('story', 'atual', 'Estados Unidos', NULL, 'Repórter freelancer que segue pistas sobre desaparecimentos'),
('story', 'atual', 'Estados Unidos', NULL, 'Arqueólogo urbano que cataloga achados em demolições antigas');
